name: CI-CD Spring Boot Java with Trivy, SonarCloud and Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vulnerabilities-scan:
    name: Scan for Vulnerabilities (Security)
    runs-on: ubuntu-latest
  
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
    
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'zulu'
    
     - name: Build project (without tests)
       run: mvn clean install -DskipTests
    
     - name: Install Trivy
       run: |
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    
     - name: Scan for vulnerabilities in dependencies (Maven)
       run: |
         trivy fs \
           --scanners vuln \
           --vuln-type library \
           --severity CRITICAL,HIGH \
           --exit-code 1 \
           --ignore-unfixed \
           --format table \
           .
           
  build-and-sonar:
    name: Build & SonarCloud Analysis (Quality)
    needs: vulnerabilities-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build com Maven (testes inclusos)
        run: mvn -B clean verify

      - name: Análise no SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube results
        run: |
          SONAR_URL="https://sonarcloud.io/api/measures/component?componentKey=vekclient&branch=main"
          CODE_SMELL=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL&metricKeys=code_smells" | jq -r '.component.measures[0].value')
          echo ""
          echo "Code Smell: ${CODE_SMELL}%" 
          if [ "$CODE_SMELL" -gt 10 ]; then
            echo "Aplicação com mais de 10 code smell."
            exit 1
          fi
          DUPLICATED=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL&metricKeys=duplicated_lines_density" | jq -r '.component.measures[0].value')
          echo ""
          echo "Código duplicado: ${DUPLICATED}%" 
          if (( $(echo "$DUPLICATED > 14.0" | bc -l) )); then
            echo "Aplicação com mais de 3% de duplicação de código."
            exit 1
          fi
          NUM_BUGS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL&metricKeys=bugs" | jq -r '.component.measures[0].value')
          echo ""
          echo "Bugs: ${NUM_BUGS}" 
          if [ "$NUM_BUGS" -gt 2 ]; then
            echo "Aplicação contem mais de 2 bugs."
            exit 1
          fi
          COVER=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL&metricKeys=coverage" | jq -r '.component.measures[0].value')
          echo ""
          echo "Cobertura da aplicação: ${COVER}%" 
          if (( $(echo "$COVER < 80.0" | bc -l) )); then
            echo "Aplicação com menos de 80% de coverage."
            # exit 1
          fi

  docker-publish:
    name: Build & Push Docker Image (Deploy)
    needs: build-and-sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Projeto
        run: mvn clean install -DskipTests

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/vekrest-vekclient:latest
            ${{ secrets.DOCKERHUB_USER }}/vekrest-vekclient:${{ github.sha }}
